# config.yaml

cuda_visible_devices: "6,7"
num_gpus: 2

token_select_pattern: "default"
data_prop: 1.0
random_seed: 42

batch_size_per_gpu: 2
gradient_accumulation_steps: 4
max_seq_length: 4096
num_train_epochs: 2
learning_rate: 5e-5 
lr_scheduler_type: "linear"
warmup_ratio: 0.03
weight_decay: 0.0
checkpointing_steps: 25
logging_steps: 50
with_prompt_token: false

use_lora: true
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.1
use_qlora: false

with_tracking: true
report_to: "tensorboard"

accelerate_config_file: "/home/panhao/project/SQLI/config/fsdp_config.yaml"
mixed_precision: "bf16"
main_process_port: 29522

merge:
  save_tokenizer: true
  use_fast_tokenizer: true
  qlora: false
  device: "auto"  # 可选: "auto", "cuda", "cuda:0", "cpu" 等。auto 会自动选择可用的 GPU
  # cuda_visible_devices: "3"  # 可选：指定 merge 使用的 GPU（如果与训练不同）